// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/login": {
    params: {};
  };
  "/workspace": {
    params: {};
  };
  "/oauth/google/callback": {
    params: {};
  };
};

type RouteFiles = {
  "root.tsx": {
    id: "root";
    page: "/" | "/login" | "/workspace" | "/oauth/google/callback";
  };
  "routes/home.tsx": {
    id: "routes/home";
    page: "/";
  };
  "routes/login.tsx": {
    id: "routes/login";
    page: "/login";
  };
  "routes/workspace.tsx": {
    id: "routes/workspace";
    page: "/workspace";
  };
  "routes/oauth.google.callback.tsx": {
    id: "routes/oauth.google.callback";
    page: "/oauth/google/callback";
  };
};